---
- name: Get vector dist
  ansible.builtin.get_url:
    url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-1.x86_64.rpm"
    dest: "./vector-{{ vector_version }}-1.x86_64.rpm"
  tags:
    - vector
- name: Install vector packages
  become: true
  ansible.builtin.yum:
    disable_gpg_check: true
    name: vector-0.29.1-1.x86_64.rpm
  notify: Start vector service
  tags:
    - vector
- name: Copy server configuration file
  ansible.builtin.template:
    src: vector.toml
    dest: "/etc/vector/vector.toml"
    mode: 0644
